#!/usr/bin/env bash
# Agent Host Worker installer. Outbound HTTPS only; nothing listens publicly.
#   sudo bash install-host.sh diagnose [--control-plane URL]
# install-host-standalone.sh is the same installer with the worker source embedded
# (generated by embed-worker-source.sh); it needs no GitHub access at install time.
#   sudo bash install-host.sh install --control-plane URL --host-id ID --ref COMMIT_SHA [--name NAME] [--token-file PATH] [--worker-src-dir DIR]
#   sudo bash install-host.sh status
# The host credential never appears in arguments, environment, logs or output. It lives in a 0600 file; only its SHA-256 digest is printed.
set -euo pipefail
set +x
ROOT=/opt/agent-host; APPS=/srv/agent-apps; SVC_USER=agent-host; REPO=mceeomoba/Universe-AGT
EMBEDDED_WORKER_B64=""
EMBEDDED_SHA256=""
log() { printf '[agent-host] %s\n' "$*"; }
die() { printf '[agent-host] ERROR: %s\n' "$*" >&2; exit 1; }
redact() { sed -E 's/[0-9a-fA-F]{40,}/<redacted>/g; s/(Bearer )[^ "]+/\1<redacted>/g'; }
need_root() { [ "$(id -u)" -eq 0 ] || die "run with sudo, for example: sudo bash $0 ${CMD:-install} ..."; }
nodearch() { case "$(uname -m)" in x86_64) echo x64;; aarch64|arm64) echo arm64;; *) die "unsupported CPU $(uname -m)";; esac; }

CMD="${1:-}"; [ -n "$CMD" ] && shift || true
CP=""; HOST_ID=""; REF=""; NAME="$(hostname)"; TOKEN_SRC=""; SRC_DIR=""
while [ $# -gt 0 ]; do
  case "$1" in
    --control-plane) CP="${2:-}"; shift 2;; --host-id) HOST_ID="${2:-}"; shift 2;; --ref) REF="${2:-}"; shift 2;;
    --name) NAME="${2:-}"; shift 2;; --token-file) TOKEN_SRC="${2:-}"; shift 2;; --worker-src-dir) SRC_DIR="${2:-}"; shift 2;;
    *) die "unknown option $1";;
  esac
done

diagnose() {
  local bad=0; log "Diagnostic (no changes are made, nothing secret is read)"
  . /etc/os-release 2>/dev/null || true
  log "OS: ${PRETTY_NAME:-unknown}   CPU: $(uname -m)   kernel: $(uname -r)"
  case "${ID:-}${ID_LIKE:-}" in *debian*|*ubuntu*) log "distro: supported (Debian/Ubuntu family)";; *) log "distro: NOT supported yet"; bad=1;; esac
  case "$(uname -m)" in x86_64|aarch64|arm64) log "CPU: supported";; *) log "CPU: NOT supported"; bad=1;; esac
  if [ "$(id -u)" -eq 0 ]; then log "privileges: root"; elif sudo -n true 2>/dev/null; then log "privileges: sudo works"; else log "privileges: need root (run with sudo)"; bad=1; fi
  INIT1="$(cat /proc/1/comm 2>/dev/null || echo unknown)"
  if [ -d /run/systemd/system ]; then log "init: systemd (service mode)"; else log "init: PID 1 is '$INIT1', no systemd - container-style box; the worker runs under a supervisor loop instead"; fi
  if command -v crontab >/dev/null 2>&1; then log "cron: yes (worker can restart after reboot via @reboot)"; else log "cron: NO (no automatic restart after a reboot; a reboot means re-running the install or the supervisor by hand)"; fi
  { [ -f /.dockerenv ] || [ -f /run/.containerenv ]; } && log "container marker: yes (this is a container, not a full VM; Docker-in-container needs privilege or a mounted socket)" || true
  if command -v docker >/dev/null 2>&1; then if docker info >/dev/null 2>&1; then log "docker: installed and running"; elif [ -S /var/run/docker.sock ]; then log "docker: CLI present, socket exists but not usable by this user (permissions?)"; else log "docker: installed but not running (installer will try to start dockerd; inside a container that needs privileges)"; fi; else log "docker: not installed (installer will install docker.io; inside a container it also needs privileges to run)"; fi
  command -v node >/dev/null 2>&1 && log "system node: $(node -v) (ignored; the installer uses its own private Node 22)" || log "system node: none (fine)"
  log "free disk /opt: $(df -h /opt 2>/dev/null | awk 'NR==2{print $4}')   RAM: $(awk '/MemTotal/{printf "%.1f GB", $2/1048576}' /proc/meminfo)"
  log "network triage (curl only, 10s cap per probe, no ping needed)"
  probe() { local u="$1" why="$2" r; r=$(curl -sS -o /dev/null -w 'http=%{http_code} dns=%{time_namelookup}s tcp=%{time_connect}s tls=%{time_appconnect}s' --max-time 10 "$u" 2>&1 || true); [ -z "$r" ] && r="fail (no reply within 10s)"; log "probe $u: $r  [$why]"; case "$r" in http=*) return 0;; *) return 1;; esac; }
  local cphost; cphost=$(printf '%s' "${CP:-https://supabase.co}" | sed -E 's|https?://([^/]+).*|\1|')
  for h in nodejs.org github.com "$cphost"; do getent hosts "$h" >/dev/null 2>&1 && log "dns $h: resolves" || log "dns $h: FAIL (name resolution broken for this host)"; done
  if command -v curl >/dev/null 2>&1; then
    probe https://1.1.1.1 "raw egress without DNS; any http line means outbound internet works" || true
    probe https://nodejs.org "required: private Node download" || bad=1
    [ -n "$CP" ] && { probe "$CP" "required: control plane" || bad=1; }
    probe https://archive.ubuntu.com "apt packages" || true
    probe https://deb.debian.org "apt packages (Debian)" || true
    probe https://registry-1.docker.io/v2/ "Docker images; 401 still means reachable" || true
    if [ -n "$EMBEDDED_WORKER_B64" ]; then log "worker source: embedded in this script, GitHub NOT needed"; else probe https://codeload.github.com "worker source download; use install-host-standalone.sh if blocked" || true; fi
  else log "curl: missing (installer will install it)"; fi
  [ "$bad" -eq 0 ] && log "RESULT: READY to install" || { log "RESULT: NOT READY, fix the items marked above"; return 1; }
}

install_cmd() {
  need_root; [ "$(uname -s)" = Linux ] || die "Linux only"
  [ -n "$CP" ] || die "--control-plane is required"; [ -n "$HOST_ID" ] || die "--host-id is required (the id the operator registered)"
  case "$CP" in https://*|http://127.0.0.1*|http://localhost*) ;; *) die "control plane must be https:// (http only for loopback tests)";; esac
  [[ "$HOST_ID" =~ ^[A-Za-z0-9_-]{1,64}$ ]] || die "--host-id has unexpected characters"
  [ -n "$REF" ] || [ -n "$SRC_DIR" ] || [ -n "$EMBEDDED_WORKER_B64" ] || die "--ref (commit SHA of the worker source) is required"
  [ -z "$REF" ] || [[ "$REF" =~ ^[0-9a-f]{7,40}$ ]] || die "--ref must be a commit SHA"
  local NA; NA="$(nodearch)"; . /etc/os-release 2>/dev/null || true
  case "${ID:-}${ID_LIKE:-}" in *debian*|*ubuntu*) ;; *) die "only Debian/Ubuntu are supported right now";; esac
  export DEBIAN_FRONTEND=noninteractive
  local MODE=supervisor; [ -d /run/systemd/system ] && MODE=systemd
  log "run mode: $MODE (PID 1 is '$(cat /proc/1/comm 2>/dev/null || echo unknown)')"
  log "installing base packages"; apt-get update -y >/dev/null; apt-get install -y ca-certificates curl tar xz-utils >/dev/null
  command -v docker >/dev/null 2>&1 || { log "installing Docker"; apt-get install -y docker.io >/dev/null; }
  if ! docker info >/dev/null 2>&1; then
    if [ "$MODE" = systemd ]; then systemctl enable --now docker >/dev/null 2>&1 || true
    elif command -v dockerd >/dev/null 2>&1; then
      log "no systemd: starting dockerd directly (logs in $ROOT/logs/dockerd.log)"; mkdir -p "$ROOT/logs"
      ( setsid dockerd >>"$ROOT/logs/dockerd.log" 2>&1 < /dev/null & )
      local i; for i in $(seq 1 15); do docker info >/dev/null 2>&1 && break; sleep 1; done
    fi
  fi
  docker info >/dev/null 2>&1 || die "Docker is not running and could not be started. Inside a container it needs privileges (or a mounted /var/run/docker.sock). Without Docker the worker can install but cannot run deployments."
  id "$SVC_USER" >/dev/null 2>&1 || useradd --system --home "$ROOT" --shell /usr/sbin/nologin "$SVC_USER"
  usermod -aG docker "$SVC_USER"
  mkdir -p "$ROOT"/{worker,config,logs,cache,runtime,node} "$APPS"

  # Private Node >= 20 (never the distro package). Checksum verified against nodejs.org's published SHASUMS256.txt.
  if [ -x "$ROOT/node/bin/node" ] && "$ROOT/node/bin/node" -e 'process.exit(+process.versions.node.split(".")[0]>=20?0:1)'; then log "private Node present: $("$ROOT/node/bin/node" -v)"
  else
    local base=https://nodejs.org/dist/latest-v22.x tmp; tmp="$(mktemp -d)"
    curl -fsSL "$base/SHASUMS256.txt" -o "$tmp/SUMS" || die "cannot reach nodejs.org"
    local line; line="$(grep "linux-$NA.tar.xz\$" "$tmp/SUMS" | head -1)"; [ -n "$line" ] || die "no Node build for $NA"
    local sum file; sum="${line%% *}"; file="${line##* }"
    log "downloading Node ($file)"; curl -fsSL "$base/$file" -o "$tmp/$file"
    ( cd "$tmp" && echo "$sum  $file" | sha256sum -c - >/dev/null ) || die "Node checksum mismatch, aborting"
    rm -rf "$ROOT/node"; mkdir -p "$ROOT/node"; tar -xJf "$tmp/$file" -C "$ROOT/node" --strip-components=1; rm -rf "$tmp"
    log "installed private Node $("$ROOT/node/bin/node" -v)"
  fi

  # Worker source: a commit-pinned tarball (content-addressed) or a local directory.
  local stage; stage="$(mktemp -d)"
  if [ -n "$SRC_DIR" ]; then [ -d "$SRC_DIR/src" ] || die "--worker-src-dir has no src/"; cp -a "$SRC_DIR"/. "$stage/"
  elif [ -n "$EMBEDDED_WORKER_B64" ]; then
    printf '%s' "$EMBEDDED_WORKER_B64" | base64 -d > "$stage/src.tgz" || die "embedded payload is corrupt (base64)"
    echo "$EMBEDDED_SHA256  $stage/src.tgz" | sha256sum -c - >/dev/null || die "embedded payload checksum mismatch"
    mkdir "$stage/x"; tar -xzf "$stage/src.tgz" -C "$stage/x"; cp -a "$stage"/x/host-worker/. "$stage/"; rm -rf "$stage/x" "$stage/src.tgz"
    log "using embedded worker source (sha256 verified, no download needed)"
  else
    curl -fsSL "https://codeload.github.com/$REPO/tar.gz/$REF" -o "$stage/src.tgz" || die "cannot download worker source for $REF"
    mkdir "$stage/x"; tar -xzf "$stage/src.tgz" -C "$stage/x"; cp -a "$stage"/x/*/agent-host-platform/host-worker/. "$stage/" ; rm -rf "$stage/x" "$stage/src.tgz"
  fi
  rm -rf "$ROOT/worker"; mkdir -p "$ROOT/worker"; cp -a "$stage"/. "$ROOT/worker/"; rm -rf "$stage"

  # Host credential: generated here, 0600, never printed. Only its SHA-256 digest is shown.
  local TF="$ROOT/config/host.token"
  if [ -n "$TOKEN_SRC" ]; then [ -s "$TOKEN_SRC" ] || die "--token-file is empty or unreadable"; ( umask 077; tr -d '[:space:]' < "$TOKEN_SRC" > "$TF" )
  elif [ ! -s "$TF" ]; then ( umask 077; head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' > "$TF" ); log "generated a new host credential (stored root-readable only)"
  else log "keeping existing host credential"; fi
  chown "$SVC_USER:$SVC_USER" "$TF"; chmod 600 "$TF"
  local DIGEST; DIGEST="$(sha256sum "$TF" | cut -d' ' -f1)"
  cat > "$ROOT/config/worker.env" <<ENV
AGENT_HOST_CONTROL_PLANE=$CP
AGENT_HOST_ID=$HOST_ID
AGENT_HOST_NAME=$NAME
AGENT_HOST_ROOT=$ROOT
AGENT_APPS_DIR=$APPS
AGENT_HOST_TOKEN_FILE=$TF
ENV
  chmod 644 "$ROOT/config/worker.env"; chown -R "$SVC_USER:$SVC_USER" "$ROOT" "$APPS"; chmod 600 "$TF"
  if [ "$MODE" = systemd ]; then
    install -m 644 "$ROOT/worker/systemd/agent-host-worker.service" /etc/systemd/system/agent-host-worker.service; systemctl daemon-reload
    echo systemd > "$ROOT/config/run-mode"
  else
    cat > "$ROOT/supervise.sh" <<'SUP'
#!/usr/bin/env bash
# Restart-on-crash supervisor for the host worker (used on hosts without systemd).
set -u
ROOT=/opt/agent-host; SVC_USER=agent-host
mkdir -p "$ROOT/runtime" "$ROOT/logs"
echo $$ > "$ROOT/runtime/supervisor.pid"
backoff=1
while :; do
  start_ts=$(date +%s)
  runuser -u "$SVC_USER" -- bash -c 'set -a; . /opt/agent-host/config/worker.env; set +a; exec /opt/agent-host/node/bin/node /opt/agent-host/worker/src/index.js' >> "$ROOT/logs/worker.log" 2>&1
  rc=$?
  now=$(date +%s); [ $((now - start_ts)) -gt 60 ] && backoff=1
  printf '%s worker exited (code %s), restarting in %ss
' "$(date -Is)" "$rc" "$backoff" >> "$ROOT/logs/supervisor.log"
  sleep "$backoff"; backoff=$(( backoff < 60 ? backoff * 2 : 60 ))
done
SUP
    chmod 755 "$ROOT/supervise.sh"; echo supervisor > "$ROOT/config/run-mode"
    if command -v crontab >/dev/null 2>&1; then
      ( crontab -l 2>/dev/null | grep -v 'agent-host/supervise.sh' || true; echo '@reboot /opt/agent-host/supervise.sh' ) | crontab -
      log "registered cron @reboot so the worker restarts after a reboot"
    else
      log "no cron on this box: after a reboot the worker does NOT restart by itself (re-run this install or: sudo setsid bash $ROOT/supervise.sh >/dev/null 2>&1 &)"
    fi
  fi
  echo; log "HOST ID:        $HOST_ID"; log "token sha256:   $DIGEST"
  log "Give the operator the two lines above so the control plane can accept this host. The credential itself never leaves this machine."

  # Real proof before enabling: one authenticated heartbeat as the service user.
  log "checking an authenticated heartbeat against the control plane"
  if ! out="$(runuser -u "$SVC_USER" -- bash -c "set -a; . $ROOT/config/worker.env; set +a; exec $ROOT/node/bin/node $ROOT/worker/src/index.js --check" 2>&1)"; then
    printf '%s\n' "$out" | redact >&2
    die "the control plane did not accept the heartbeat. Once the operator has registered the digest above, run this same install command again."
  fi
  printf '%s\n' "$out" | redact
  systemctl enable --now agent-host-worker.service; sleep 3
  systemctl is-active --quiet agent-host-worker.service || { journalctl -u agent-host-worker -n 30 --no-pager | redact; die "service failed to start"; }
  log "DONE: worker running and authenticated. It restarts on crash and after reboot."
}

status_cmd() {
  need_root
  if [ "$(cat "$ROOT/config/run-mode" 2>/dev/null)" = supervisor ]; then
    local SPID=""; [ -s "$ROOT/runtime/supervisor.pid" ] && SPID="$(cat "$ROOT/runtime/supervisor.pid")"
    if [ -n "$SPID" ] && kill -0 "$SPID" 2>/dev/null; then log "supervisor: running (pid $SPID)"; else log "supervisor: NOT running"; fi
    tail -n 10 "$ROOT/logs/supervisor.log" "$ROOT/logs/worker.log" 2>/dev/null | redact || true
  else
    systemctl is-active agent-host-worker.service || true; journalctl -u agent-host-worker -n 15 --no-pager 2>/dev/null | redact || true
  fi
  runuser -u "$SVC_USER" -- bash -c "set -a; . $ROOT/config/worker.env; set +a; exec $ROOT/node/bin/node $ROOT/worker/src/index.js --check" 2>&1 | redact || true
}

case "$CMD" in diagnose) diagnose;; install) install_cmd;; status) status_cmd;; *) echo "usage: sudo bash $0 diagnose|install|status (see header for options)"; exit 2;; esac
