import type {FastifyInstance}from'fastify';import{z}from'zod';import{createHash}from'node:crypto';import type{Store}from'../api/store.js';import{event}from'../api/store.js';import{requireScope,Principal}from'../authentication/auth.js';import{id,version}from'../api/validation.js';
// Only the server receives the storage service key. Agents receive short-lived scoped URLs.
export function artifacts(api:FastifyInstance,store:Store){
 const base=process.env.SUPABASE_URL,key=process.env.SUPABASE_STORAGE_KEY,bucket='universe-artifacts';
 const configured=()=>{if(!base||!key)throw Object.assign(new Error('Storage unavailable'),{statusCode:503})};
 async function storage(path:string,method:string,body?:object){configured();const r=await fetch(base+'/storage/v1/'+path,{method,headers:{Authorization:'Bearer '+key,apikey:key!,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});if(!r.ok)throw Object.assign(new Error('Storage request failed'),{statusCode:503});return r.json()}
 api.post('/v1/artifacts',async req=>{const p=(req as any).principal as Principal;requireScope(p,'manage_artifacts');const b=z.object({project_id:id,filename:z.string().regex(/^[a-zA-Z0-9_.-]{1,100}\.tar\.gz$/),checksum:z.string().regex(/^[a-f0-9]{64}$/),size:z.number().int().positive().max(104857600),version}).strict().parse(req.body);configured();return store.tx(p,async q=>{const artifact=crypto.randomUUID(),path=`${p.tenant_id}/${b.project_id}/${artifact}.tar.gz`;const r=(await q.query('INSERT INTO universe.artifacts(id,tenant_id,project_id,filename,storage_path,checksum,size,version)VALUES($1,$2,$3,$4,$5,$6,$7,$8)RETURNING *',[artifact,p.tenant_id,b.project_id,b.filename,path,b.checksum,b.size,b.version])).rows[0];const signed=await storage('object/upload/sign/'+bucket+'/'+path,'POST',{});await event(q,p,'artifact.created',r.id);return{artifact:r,upload_url:base+'/storage/v1'+signed.url,expires_in:7200}})});
 api.post('/v1/artifacts/:id/finalize',async req=>{const p=(req as any).principal as Principal;requireScope(p,'manage_artifacts');const artifact=id.parse((req.params as any).id);return store.tx(p,async q=>{const a=(await q.query('SELECT * FROM universe.artifacts WHERE id=$1 FOR UPDATE',[artifact])).rows[0];if(!a)throw Object.assign(new Error('Not found'),{statusCode:404});configured();const response=await fetch(base+'/storage/v1/object/'+bucket+'/'+a.storage_path,{headers:{Authorization:'Bearer '+key,apikey:key!},signal:AbortSignal.timeout(60000)});if(!response.ok||!response.body)throw Object.assign(new Error('Artifact unavailable'),{statusCode:400});const hash=createHash('sha256');let size=0;for await(const chunk of response.body as any){size+=chunk.length;if(size>Number(a.size)||size>104857600){await response.body.cancel().catch(()=>{});throw Object.assign(new Error('Artifact size mismatch'),{statusCode:400})}hash.update(chunk)}if(size!==Number(a.size)||hash.digest('hex')!==a.checksum)throw Object.assign(new Error('Artifact checksum mismatch'),{statusCode:400});await q.query('UPDATE universe.artifacts SET verified=true WHERE id=$1',[artifact]);await event(q,p,'artifact.verified',artifact);return{id:artifact,verified:true}})});
 api.get('/v1/artifacts/:id',async req=>{const p=(req as any).principal as Principal;requireScope(p,p.kind==='host'?'worker':'read_status');return store.tx(p,async q=>{const a=(await q.query('SELECT * FROM universe.artifacts WHERE id=$1 AND verified',[id.parse((req.params as any).id)])).rows[0];if(!a)throw Object.assign(new Error('Not found'),{statusCode:404});if(p.kind==='host'){const assigned=(await q.query("SELECT 1 FROM universe.tasks WHERE assigned_to=$1 AND payload->>'artifact_id'=$2 AND status IN('claimed','running') AND lease_expires_at>now()",[p.subject_id,a.id])).rows[0];if(!assigned)throw Object.assign(new Error('Forbidden'),{statusCode:403})}const signed=await storage('object/sign/'+bucket+'/'+a.storage_path,'POST',{expiresIn:120});return{artifact:a,download_url:base+'/storage/v1'+signed.signedURL,expires_in:120}})});
}
