import {artifacts} from '../artifacts/routes.js';
import Fastify,{FastifyRequest}from'fastify';import rateLimit from'@fastify/rate-limit';import pg from'pg';import{randomUUID}from'node:crypto';import{z}from'zod';import{Store,event}from'./store.js';import{digest,mint,requireScope,requireHost,Principal,permissions}from'../authentication/auth.js';import*as v from'./validation.js';
export function app(store:Store,{allowHttp=false}={}){
 const api=Fastify({bodyLimit:65536,logger:{redact:['req.headers.authorization','req.body','res.body']},trustProxy:false});
 api.register(rateLimit,{max:120,timeWindow:'1 minute'});
 api.decorateRequest('principal',null);
 api.addHook('onRequest',async(req,reply)=>{if(req.url==='/health')return;if(!allowHttp&&req.protocol!=='https')return reply.code(426).send({error:'HTTPS_REQUIRED'});const auth=req.headers.authorization;if(!auth?.startsWith('Bearer agt_'))return reply.code(401).send({error:'UNAUTHORIZED'});const p=await store.authenticate(digest(auth.slice(7)));if(!p)return reply.code(401).send({error:'UNAUTHORIZED'});(req as any).principal=p});
 api.setErrorHandler((e,req,reply)=>{const err=e as any;const status=err instanceof z.ZodError?400:err.statusCode||(['23503','23505','23514','22P02'].includes(err.code)?400:500);req.log.warn({code:err.code||'REQUEST_FAILED',status},'Request failed');reply.code(status).send({error:status===500?'INTERNAL_ERROR':status===403?'FORBIDDEN':status===409?'CONFLICT':status===404?'NOT_FOUND':'INVALID_REQUEST'})});
 const p=(req:FastifyRequest)=>(req as any).principal as Principal;
 const param=(req:FastifyRequest)=>(req.params as any).id as string;
 const sanitize=(row:any)=>{if(!row)return row;const{lease_token,request_hash,...safe}=row;return safe};
 const notFound=()=>{throw Object.assign(new Error('Not found'),{statusCode:404})};
 const conflict=()=>{throw Object.assign(new Error('Conflict'),{statusCode:409})};
 api.get('/health',async()=>({status:'ok',version:'0.1.0'}));
 for(const kind of ['agent','host']as const)api.post(`/v1/${kind}s/register`,async(req)=>{const who=p(req);requireScope(who,`register_${kind}`);if(who.kind!=='operator')requireScope(who,'approve');const b=v.register.parse(req.body);return store.tx(who,async q=>{const cols=kind==='agent'?'type':'host_type',row=(await q.query(`INSERT INTO universe.${kind}s(tenant_id,name,${cols},capabilities) VALUES($1,$2,$3,$4) ON CONFLICT(tenant_id,name) DO NOTHING RETURNING *`,[who.tenant_id,b.name,b.type||(kind==='agent'?'custom-agent':'persistent-linux-host'),b.capabilities])).rows[0];if(!row)conflict();await event(q,who,`${kind}.registered`,row.id);return row})});
 api.post('/v1/credentials',async(req)=>{const who=p(req);requireScope(who,'approve');if(who.kind!=='operator')throw Object.assign(new Error('Forbidden'),{statusCode:403});const b=z.object({subject_id:v.id,kind:z.enum(['agent','host']),scopes:z.array(z.enum(permissions)).min(1).max(15),expires_in_days:z.number().int().min(1).max(90).default(30)}).strict().parse(req.body);for(const scope of b.scopes)if(!who.scopes.includes(scope))throw Object.assign(new Error('Forbidden'),{statusCode:403});const token=mint();return store.tx(who,async q=>{const found=(await q.query(`SELECT id FROM universe.${b.kind}s WHERE id=$1`,[b.subject_id])).rows[0];if(!found)notFound();const r=await q.query('SELECT universe.issue_credential($1,$2,$3,$4,$5,$6)',[who.tenant_id,b.subject_id,b.kind,digest(token),b.scopes,b.expires_in_days]);await event(q,who,'credential.issued',b.subject_id,{kind:b.kind});return{credential_id:r.rows[0].issue_credential,token,expires_in_days:b.expires_in_days}})});
 api.post('/v1/credentials/rotate',async(req)=>{const who=p(req);requireScope(who,'rotate');const token=mint();return store.tx(who,async q=>{await q.query('SELECT universe.rotate_credential($1,$2,$3)',[who.tenant_id,who.credential_id,digest(token)]);await event(q,who,'credential.rotated',who.subject_id);return{token}})});
 api.post('/v1/projects',async(req)=>{const who=p(req);requireScope(who,'manage_projects');const b=v.project.parse(req.body);return store.tx(who,async q=>{const r=(await q.query('INSERT INTO universe.projects(tenant_id,name,owner,repository,runtime) VALUES($1,$2,$3,$4,$5) RETURNING *',[who.tenant_id,b.name,who.subject_id,b.repository,b.runtime])).rows[0];await event(q,who,'project.created',r.id);return r})});
 const createTask=async(who:Principal,body:unknown)=>{const b=v.task.parse(body);requireScope(who,b.type==='deploy'||['update','build','docker-build','docker-run','docker-compose'].includes(b.type)?'deploy':b.type==='healthcheck'||b.type==='system-info'||b.type==='status'?'read_status':b.type==='logs'?'read_logs':b.type==='artifact-upload'||b.type==='artifact-download'?'manage_artifacts':b.type==='environment-update'?'deploy':b.type);if(['deploy','update'].includes(b.type)&&(!b.artifact_id||!b.project_id||!b.version))throw Object.assign(new Error('Missing deployment fields'),{statusCode:400});const hash=digest(JSON.stringify(b));return store.tx(who,async q=>{const existing=(await q.query('SELECT * FROM universe.tasks WHERE created_by=$1 AND idempotency_key=$2',[who.subject_id,b.idempotency_key])).rows[0];if(existing){if(existing.request_hash!==hash)conflict();return existing}const host=(await q.query('SELECT * FROM universe.hosts WHERE id=$1',[b.host_id])).rows[0];if(!host)notFound();if(!host.capabilities.includes(b.type))throw Object.assign(new Error('Unsupported'),{statusCode:400});if(b.artifact_id){const a=(await q.query('SELECT id FROM universe.artifacts WHERE id=$1 AND project_id=$2 AND verified',[b.artifact_id,b.project_id])).rows[0];if(!a)throw Object.assign(new Error('Invalid artifact'),{statusCode:400})}const r=(await q.query('INSERT INTO universe.tasks(tenant_id,created_by,assigned_to,type,status,priority,payload,idempotency_key,request_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(tenant_id,created_by,idempotency_key) DO NOTHING RETURNING *',[who.tenant_id,who.subject_id,b.host_id,b.type,b.mode==='manual'?'awaiting_approval':'queued',b.priority,b,b.idempotency_key,hash])).rows[0];if(!r){const old=(await q.query('SELECT * FROM universe.tasks WHERE created_by=$1 AND idempotency_key=$2',[who.subject_id,b.idempotency_key])).rows[0];if(old.request_hash!==hash)conflict();return old}if(['deploy','update'].includes(b.type))await q.query('INSERT INTO universe.deployments(tenant_id,task_id,project_id,host_id,version) VALUES($1,$2,$3,$4,$5)',[who.tenant_id,r.id,b.project_id,b.host_id,b.version]);await event(q,who,'task.created',r.id,{type:b.type,mode:b.mode});return r})};
 api.post('/v1/tasks',req=>createTask(p(req),req.body));api.post('/v1/deployments',req=>createTask(p(req),{...(req.body as object),type:'deploy'}));
 for(const action of ['approve','reject','cancel'])api.post(`/v1/tasks/:id/${action}`,async(req)=>{const who=p(req),id=v.id.parse(param(req));requireScope(who,action==='cancel'?'deploy':'approve');return store.tx(who,async q=>{const task=(await q.query('SELECT * FROM universe.tasks WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!task)notFound();if(who.kind!=='operator'&&task.created_by!==who.subject_id)throw Object.assign(new Error('Forbidden'),{statusCode:403});if(action!=='cancel'&&task.status!=='awaiting_approval')conflict();if(['claimed','running','completed','failed'].includes(task.status))conflict();const status=action==='approve'?'queued':'cancelled';await q.query('UPDATE universe.tasks SET status=$2,updated_at=now() WHERE id=$1',[id,status]);await event(q,who,action==='approve'?'deployment.approved':'task.cancelled',id);return{id,status}})});
 api.post('/v1/hosts/:id/heartbeat',async(req)=>{const who=p(req),id=v.id.parse(param(req));requireHost(who,id);const b=v.heartbeat.parse(req.body);return store.tx(who,async q=>{const row=(await q.query('UPDATE universe.hosts SET status=$2,last_seen=now(),worker_version=$3,capabilities=$4,metadata=$5,updated_at=now() WHERE id=$1 RETURNING id,last_seen',[id,'online',b.worker_version,b.capabilities,b])).rows[0];if(!row)notFound();return row})});
 api.post('/v1/hosts/:id/tasks/claim',async(req)=>{const who=p(req),id=v.id.parse(param(req));requireHost(who,id);return store.tx(who,async q=>{const exhausted=(await q.query("UPDATE universe.tasks SET status='failed',error='LEASE_EXHAUSTED',completed_at=now(),updated_at=now() WHERE assigned_to=$1 AND attempt>=5 AND status IN('claimed','running') AND lease_expires_at<now() RETURNING id",[id])).rows;for(const t of exhausted){await q.query("UPDATE universe.deployments SET status='failed',health_status='unknown',updated_at=now() WHERE task_id=$1",[t.id]);await event(q,who,'task.failed',t.id,{code:'LEASE_EXHAUSTED'})}const task=(await q.query("SELECT t.* FROM universe.tasks t JOIN universe.hosts h ON h.id=t.assigned_to WHERE t.assigned_to=$1 AND t.type=ANY(h.capabilities) AND(t.status IN('queued','retrying') OR(t.status IN('claimed','running') AND t.lease_expires_at<now())) AND t.attempt<5 ORDER BY t.priority DESC,t.created_at FOR UPDATE OF t SKIP LOCKED LIMIT 1",[id])).rows[0];if(!task)return{task:null};const lease=randomUUID(),r=(await q.query("UPDATE universe.tasks SET status='claimed',lease_token=$2,lease_expires_at=now()+interval '90 seconds',attempt=attempt+1,updated_at=now() WHERE id=$1 RETURNING *",[task.id,lease])).rows[0];await event(q,who,'task.claimed',task.id,{attempt:r.attempt});return{task:r,lease_token:lease,lease_expires_at:r.lease_expires_at}})});
 for(const action of ['start','renew','complete','fail'])api.post(`/v1/tasks/:id/${action}`,async(req)=>{const who=p(req),id=v.id.parse(param(req)),b=action==='complete'?v.complete.parse(req.body):action==='fail'?v.fail.parse(req.body):v.lease.parse(req.body);requireHost(who,who.subject_id);return store.tx(who,async q=>{const t=(await q.query('SELECT * FROM universe.tasks WHERE id=$1 AND assigned_to=$2 AND lease_token=$3 AND lease_expires_at>now() FOR UPDATE',[id,who.subject_id,b.lease_token])).rows[0];if(!t||!['claimed','running'].includes(t.status))conflict();if(action==='renew'){await q.query("UPDATE universe.tasks SET lease_expires_at=now()+interval '90 seconds' WHERE id=$1",[id]);return{id,status:t.status}}if(action==='start'){await q.query("UPDATE universe.tasks SET status='running',started_at=coalesce(started_at,now()),updated_at=now() WHERE id=$1",[id]);await event(q,who,'task.started',id);return{id,status:'running'}}const status=action==='complete'?'completed':'failed';await q.query('UPDATE universe.tasks SET status=$2,result=$3,error=$4,completed_at=now(),updated_at=now() WHERE id=$1',[id,status,action==='complete'?(b as z.infer<typeof v.complete>).result:null,action==='fail'?(b as z.infer<typeof v.fail>).code:null]);await q.query('UPDATE universe.deployments SET status=$2,health_status=$3,container_ids=$4,updated_at=now() WHERE task_id=$1',[id,status,action==='complete'?(b as any).result.health||'unknown':'unhealthy',action==='complete'?(b as any).result.container_ids||[]:[]]);await event(q,who,action==='complete'?'deployment.completed':'deployment.failed',id,action==='fail'?{code:(b as any).code,rolled_back:(b as any).rolled_back}:{});return{id,status}})});
 for(const table of ['agents','hosts','tasks','projects','deployments']as const){api.get(`/v1/${table}`,async(req)=>{const who=p(req);requireScope(who,'read_status');return store.tx(who,async q=>(await q.query(`SELECT * FROM universe.${table} ORDER BY created_at DESC LIMIT 100`)).rows.map(sanitize))});api.get(`/v1/${table}/:id`,async(req)=>{const who=p(req);requireScope(who,'read_status');return store.tx(who,async q=>{const row=(await q.query(`SELECT * FROM universe.${table} WHERE id=$1`,[v.id.parse(param(req))])).rows[0];if(!row)notFound();return sanitize(row)})})}
 api.get('/v1/services',async(req)=>{const who=p(req);requireScope(who,'read_status');return store.tx(who,async q=>(await q.query("SELECT id,project_id,host_id,version,status,health_status,container_ids,updated_at FROM universe.deployments WHERE status='completed'")).rows)});
 for(const action of ['start','stop','restart','rollback'])api.post(`/v1/services/:id/${action}`,async(req)=>{const who=p(req);requireScope(who,action);const dep=await store.tx(who,async q=>(await q.query('SELECT * FROM universe.deployments WHERE id=$1',[v.id.parse(param(req))])).rows[0]);if(!dep)notFound();const b=z.object({idempotency_key:z.string().min(8).max(160)}).strict().parse(req.body);return createTask(who,{type:action,host_id:dep.host_id,project_id:dep.project_id,deployment_id:dep.id,version:dep.version,idempotency_key:b.idempotency_key})});
 api.get('/v1/events',async(req)=>{const who=p(req);requireScope(who,'read_status');const after=z.coerce.number().int().nonnegative().default(0).parse((req.query as any).after);return store.tx(who,async q=>(await q.query('SELECT * FROM universe.events WHERE id>$1 ORDER BY id LIMIT 200',[after])).rows)});
 artifacts(api,store);
 return api;
}
if(process.env.NODE_ENV!=='test'&&process.argv[1]?.endsWith('/server.js')){const database=process.env.DATABASE_URL;if(!database)throw Error('DATABASE_URL required');const api=app(new Store(new pg.Pool({connectionString:database})),{allowHttp:process.env.LOCAL_HTTP==='1'});await api.listen({host:'127.0.0.1',port:Number(process.env.PORT||8080)})}
