import {z} from 'zod';
export const id=z.string().uuid(),name=z.string().regex(/^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,79}$/),version=z.string().regex(/^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,63}$/);
export const register=z.object({name,type:name.optional(),capabilities:z.array(name).max(30).default([])}).strict();
export const project=z.object({name,repository:z.string().url().optional(),runtime:z.literal('docker').default('docker')}).strict();
export const task=z.object({type:z.enum(['deploy','update','restart','stop','start','remove','rollback','logs','status','healthcheck','build','docker-build','docker-run','docker-compose','environment-update','artifact-download','artifact-upload','system-info']),host_id:id,project_id:id.optional(),artifact_id:id.optional(),deployment_id:id.optional(),version:version.optional(),mode:z.enum(['automatic','manual']).default('automatic'),priority:z.number().int().min(0).max(100).default(0),idempotency_key:z.string().min(8).max(160)}).strict();
export const heartbeat=z.object({worker_version:version,capabilities:z.array(name).max(30),cpu_percent:z.number().min(0).max(100),memory_free_bytes:z.number().int().nonnegative(),disk_free_bytes:z.number().int().nonnegative(),uptime_seconds:z.number().nonnegative(),docker:z.boolean(),applications:z.array(z.object({project_id:id,status:z.enum(['running','stopped','unhealthy','crash_loop'])}).strict()).max(100)}).strict();
export const lease=z.object({lease_token:id}).strict();
export const complete=z.object({lease_token:id,result:z.object({deployment_id:id.optional(),health:z.enum(['healthy','unhealthy']).optional(),container_ids:z.array(name).max(20).optional(),status:z.enum(['running','stopped','removed','rolled_back']).optional()}).strict()}).strict();
export const fail=z.object({lease_token:id,code:z.enum(['ARTIFACT_INVALID','MANIFEST_INVALID','BUILD_FAILED','HEALTH_FAILED','INSUFFICIENT_RESOURCES','EXECUTION_FAILED','CRASH_LOOP','LEASE_EXPIRED']),rolled_back:z.boolean().default(false)}).strict();
