import test from'node:test';import assert from'node:assert/strict';import pg from'pg';import{randomUUID,createHash}from'node:crypto';import{app}from'../control-plane/api/server.js';import{Store}from'../control-plane/api/store.js';import{mint,digest}from'../control-plane/authentication/auth.js';
test('private artifact URLs, byte checksum finalization, and assigned-host access',{skip:!process.env.TEST_DATABASE_URL},async()=>{const pool=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL}),t=randomUUID(),subject=randomUUID(),project=randomUUID(),host=randomUUID(),stranger=randomUUID(),token=mint(),hostToken=mint(),strangerToken=mint();const original=globalThis.fetch;process.env.SUPABASE_URL='https://storage.test';process.env.SUPABASE_STORAGE_KEY='local-test-fixture';const api=app(new Store(pool),{allowHttp:true});let bytes=Buffer.from('archive-fixture');globalThis.fetch=async(url:any,opts:any)=>{assert.equal(new URL(url).origin,'https://storage.test');if(String(url).includes('/upload/sign/'))return Response.json({url:'/object/upload/sign/universe-artifacts/mock?token=fixture'});if(String(url).includes('/object/sign/'))return Response.json({signedURL:'/object/sign/universe-artifacts/mock?token=fixture'});return new Response(bytes)};try{
 await pool.query('INSERT INTO universe.tenants(id,name)VALUES($1,$2)',[t,'artifact-test']);await pool.query('INSERT INTO universe.projects(id,tenant_id,name,owner)VALUES($1,$2,$3,$4)',[project,t,'sample-app',subject]);await pool.query('INSERT INTO universe.hosts(id,tenant_id,name)VALUES($1,$2,$3),($4,$2,$5)',[host,t,'assigned',stranger,'stranger']);for(const[id,tok,k,s]of[[subject,token,'operator',['manage_artifacts']],[host,hostToken,'host',['worker','read_status']],[stranger,strangerToken,'host',['worker','read_status']]])await pool.query("INSERT INTO universe.credentials(tenant_id,subject_id,kind,token_hash,scopes,expires_at)VALUES($1,$2,$3,$4,$5,now()+interval '1 hour')",[t,id,k,digest(tok as string),s]);
 const req=async(path:string,method:string,tok:string,body?:object)=>{const r=await api.inject({method:method as any,url:path,headers:{authorization:'Bearer '+tok},payload:body});return{status:r.statusCode,body:r.json()}};
 const created=await req('/v1/artifacts','POST',token,{project_id:project,filename:'sample.tar.gz',checksum:createHash('sha256').update(bytes).digest('hex'),size:bytes.length,version:'v1'});assert.equal(created.status,200);const id=created.body.artifact.id;assert.ok(created.body.upload_url.startsWith('https://storage.test/storage/v1/'));assert.equal(created.body.artifact.verified,false);
 assert.equal((await req('/v1/artifacts/'+id,'GET',hostToken)).status,404);
 bytes=Buffer.from('tampered-fixture');assert.equal((await req('/v1/artifacts/'+id+'/finalize','POST',token)).status,400);
 bytes=Buffer.from('archive-fixture');assert.equal((await req('/v1/artifacts/'+id+'/finalize','POST',token)).status,200);
 assert.equal((await req('/v1/artifacts/'+id,'GET',strangerToken)).status,403);
 await pool.query("INSERT INTO universe.tasks(tenant_id,created_by,assigned_to,type,status,payload,idempotency_key,request_hash,lease_expires_at)VALUES($1,$2,$3,'deploy','running',$4,$5,$6,now()+interval '90 seconds')",[t,subject,host,{artifact_id:id},randomUUID(),'fixture']);
 const allowed=await req('/v1/artifacts/'+id,'GET',hostToken);assert.equal(allowed.status,200);assert.equal(allowed.body.expires_in,120);assert.ok(!JSON.stringify(allowed.body).includes('local-test-fixture'));
 }finally{globalThis.fetch=original;delete process.env.SUPABASE_URL;delete process.env.SUPABASE_STORAGE_KEY;await api.close();await pool.end()}});
