import test from'node:test';import assert from'node:assert/strict';import pg from'pg';import{randomUUID}from'node:crypto';import{app}from'../control-plane/api/server.js';import{Store}from'../control-plane/api/store.js';import{mint,digest,permissions}from'../control-plane/authentication/auth.js';
test('deployment metadata and fenced completion persist; unknown resource targets rejected',{skip:!process.env.TEST_DATABASE_URL},async()=>{const pool=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL}),t=randomUUID(),subject=randomUUID(),project=randomUUID(),host=randomUUID(),artifact=randomUUID(),token=mint(),hostToken=mint(),api=app(new Store(pool),{allowHttp:true});try{
 await pool.query('INSERT INTO universe.tenants(id,name)VALUES($1,$2)',[t,'deploy-test']);await pool.query('INSERT INTO universe.projects(id,tenant_id,name,owner)VALUES($1,$2,$3,$4)',[project,t,'sample-app',subject]);await pool.query('INSERT INTO universe.hosts(id,tenant_id,name,capabilities)VALUES($1,$2,$3,$4)',[host,t,'host',['deploy','stop']]);await pool.query("INSERT INTO universe.artifacts(id,tenant_id,project_id,filename,storage_path,checksum,size,version,verified)VALUES($1,$2,$3,'app.tar.gz',$4,$5,10,'v1',true)",[artifact,t,project,randomUUID(),'f'.repeat(64)]);for(const[id,tok,k,s]of[[subject,token,'operator',permissions],[host,hostToken,'host',['worker','read_status']]])await pool.query("INSERT INTO universe.credentials(tenant_id,subject_id,kind,token_hash,scopes,expires_at)VALUES($1,$2,$3,$4,$5,now()+interval '1 hour')",[t,id,k,digest(tok as string),s]);
 const req=async(path:string,method='GET',body?:object,tok=token)=>{const r=await api.inject({method:method as any,url:path,headers:{authorization:'Bearer '+tok},payload:body});return{status:r.statusCode,body:r.json()}};
 const created=await req('/v1/deployments','POST',{project_id:project,host_id:host,artifact_id:artifact,version:'v1',idempotency_key:randomUUID()});assert.equal(created.status,200);const id=created.body.id;
 const claimed=(await req('/v1/hosts/'+host+'/tasks/claim','POST',{},hostToken)).body;assert.equal(claimed.task.payload.project,'sample-app');assert.ok(claimed.task.payload.deployment_id);
 const completed=await req('/v1/tasks/'+id+'/complete','POST',{lease_token:claimed.lease_token,result:{health:'healthy',status:'running',container_ids:['app-one']}},hostToken);assert.equal(completed.status,200);
 const deployment=(await req('/v1/deployments/'+claimed.task.payload.deployment_id)).body;assert.equal(deployment.health_status,'healthy');assert.deepEqual(deployment.container_ids,['app-one']);
 const stopped=await req('/v1/services/'+deployment.id+'/stop','POST',{idempotency_key:randomUUID()});assert.equal(stopped.status,200);assert.equal(stopped.body.payload.deployment_id,deployment.id);
 assert.equal((await req('/v1/services/'+randomUUID()+'/stop','POST',{idempotency_key:randomUUID()})).status,404);
 }finally{await api.close();await pool.end()}});
