import test from'node:test';import assert from'node:assert/strict';import pg from'pg';import{randomUUID}from'node:crypto';import{app}from'../control-plane/api/server.js';import{Store}from'../control-plane/api/store.js';import{digest,mint,permissions}from'../control-plane/authentication/auth.js';
const connection=process.env.TEST_DATABASE_URL;
test('Postgres API: tenant RLS, approval, idempotency, atomic claim, fencing and journal',{skip:!connection},async()=>{const pool=new pg.Pool({connectionString:connection}),tenant=randomUUID(),other=randomUUID(),operator=randomUUID(),host=randomUUID(),token=mint(),hostToken=mint(),otherToken=mint();const api=app(new Store(pool),{allowHttp:true});try{
 await pool.query('INSERT INTO universe.tenants(id,name)VALUES($1,$2),($3,$4)',[tenant,'qa',other,'qa-other']);
 for(const[t,s,k,tok,sc]of[[tenant,operator,'operator',token,permissions],[tenant,host,'host',hostToken,['worker','read_status']],[other,randomUUID(),'operator',otherToken,permissions]])await pool.query('INSERT INTO universe.credentials(tenant_id,subject_id,kind,token_hash,scopes,expires_at)VALUES($1,$2,$3,$4,$5,now()+interval \'1 hour\')',[t,s,k,digest(tok as string),sc]);
 await pool.query('INSERT INTO universe.hosts(id,tenant_id,name,capabilities)VALUES($1,$2,$3,$4)',[host,tenant,'qa-host',['status','deploy']]);
 const req=async(path:string,method='GET',body?:object,tok=token)=>{const r=await api.inject({method:method as any,url:path,headers:{authorization:'Bearer '+tok},payload:body});return{status:r.statusCode,body:r.json()}};
 assert.equal((await api.inject({method:'GET',url:'/v1/hosts'})).statusCode,401);
 assert.equal((await req('/v1/hosts','GET',undefined,otherToken)).body.length,0);
 const input={type:'status',host_id:host,idempotency_key:'qa-'+randomUUID(),mode:'manual'};
 const created=await req('/v1/tasks','POST',input);assert.equal(created.status,200);const id=created.body.id;
 assert.equal((await req('/v1/tasks','POST',input)).body.id,id);
 assert.equal((await req('/v1/tasks','POST',Object.fromEntries(Object.entries(input).reverse()))).body.id,id);
 assert.equal((await req('/v1/tasks','POST',{...input,mode:'automatic'})).status,409);
 assert.equal((await req('/v1/hosts/'+host+'/tasks/claim','POST',{},hostToken)).body.task,null);
 assert.equal((await req('/v1/tasks/'+id+'/approve','POST')).status,200);
 const claims=await Promise.all(Array.from({length:8},()=>req('/v1/hosts/'+host+'/tasks/claim','POST',{},hostToken)));assert.equal(claims.filter(c=>c.body.task).length,1);const claim=claims.find(c=>c.body.task)!.body;
 assert.equal((await req('/v1/tasks/'+id+'/start','POST',{lease_token:randomUUID()},hostToken)).status,409);
 assert.equal((await req('/v1/tasks/'+id+'/start','POST',{lease_token:claim.lease_token},hostToken)).status,200);
 assert.equal((await req('/v1/tasks/'+id)).body.lease_token,undefined);
 assert.equal((await req('/v1/tasks/'+id+'/renew','POST',{lease_token:claim.lease_token},hostToken)).status,200);
 assert.equal((await req('/v1/credentials','POST',{subject_id:host,kind:'host',scopes:['worker']},hostToken)).status,403);
 assert.equal((await req('/v1/credentials','POST',{subject_id:host,kind:'host',scopes:['worker']})).status,200);
 await pool.query("UPDATE universe.tasks SET lease_expires_at=now()-interval '1 second' WHERE id=$1",[id]);
 const replacement=(await req('/v1/hosts/'+host+'/tasks/claim','POST',{},hostToken)).body;assert.notEqual(replacement.lease_token,claim.lease_token);
 assert.equal((await req('/v1/tasks/'+id+'/complete','POST',{lease_token:claim.lease_token,result:{}},hostToken)).status,409);
 assert.equal((await req('/v1/tasks/'+id+'/complete','POST',{lease_token:replacement.lease_token,result:{status:'running'}},hostToken)).status,200);
 assert.equal((await req('/v1/tasks/'+id)).body.status,'completed');assert.equal((await req('/v1/tasks/'+id,'GET',undefined,otherToken)).status,404);
 assert.ok((await req('/v1/events')).body.some((e:any)=>e.type==='task.claimed'));
 await assert.rejects(pool.query('UPDATE universe.events SET type=$1 WHERE tenant_id=$2',['bad',tenant]));
 assert.equal((await req('/v1/tasks','POST',{...input,idempotency_key:'qa-'+randomUUID(),command:'rm -rf /'})).status,400);
 }finally{await api.close();await pool.end()}});
