import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import pg from'pg';import{encrypt,decrypt}from'../control-plane/secrets/crypto.js';import{app}from'../control-plane/api/server.js';import{Store}from'../control-plane/api/store.js';import{digest,mint}from'../control-plane/authentication/auth.js';
test('AEAD encryption binds secret to tenant/project/name; tampering and missing key fail',()=>{process.env.SECRETS_ENCRYPTION_KEY='a'.repeat(64);const cipher=encrypt('private fixture','tenant/project/name');assert.ok(!cipher.includes('private'));assert.equal(decrypt(cipher,'tenant/project/name'),'private fixture');assert.throws(()=>decrypt(cipher,'other/project/name'));const buf=Buffer.from(cipher,'base64');buf[buf.length-1]^=1;assert.throws(()=>decrypt(buf.toString('base64'),'tenant/project/name'));delete process.env.SECRETS_ENCRYPTION_KEY;assert.throws(()=>encrypt('x','context'))});
test('secret runtime injection is scoped to running task host + fence; audit/read views omit values',{skip:!process.env.TEST_DATABASE_URL},async()=>{const pool=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL}),tenant=randomUUID(),subject=randomUUID(),project=randomUUID(),host=randomUUID(),task=randomUUID(),lease=randomUUID(),token=mint(),hostToken=mint(),api=app(new Store(pool),{allowHttp:true});process.env.SECRETS_ENCRYPTION_KEY='b'.repeat(64);try{
 await pool.query('INSERT INTO universe.tenants(id,name)VALUES($1,$2)',[tenant,'secret-fixture']);await pool.query('INSERT INTO universe.projects(id,tenant_id,name,owner)VALUES($1,$2,$3,$4)',[project,tenant,'project',subject]);await pool.query('INSERT INTO universe.hosts(id,tenant_id,name)VALUES($1,$2,$3)',[host,tenant,'host']);for(const[id,tok,kind,scopes]of[[subject,token,'operator',['approve','read_status']],[host,hostToken,'host',['worker','read_status']]])await pool.query("INSERT INTO universe.credentials(tenant_id,subject_id,kind,token_hash,scopes,expires_at)VALUES($1,$2,$3,$4,$5,now()+interval '1 hour')",[tenant,id,kind,digest(tok as string),scopes]);
 await pool.query("INSERT INTO universe.tasks(id,tenant_id,created_by,assigned_to,type,status,payload,idempotency_key,request_hash,lease_token,lease_expires_at)VALUES($1,$2,$3,$4,'deploy','running',$5,$6,'fixture',$7,now()+interval '90 seconds')",[task,tenant,subject,host,{project_id:project,secret_refs:['API_KEY']},randomUUID(),lease]);
 const req=async(path:string,method:string,tok:string,payload?:object)=>{const r=await api.inject({method:method as any,url:path,headers:{authorization:'Bearer '+tok},payload});return{status:r.statusCode,body:r.json()}};
 assert.equal((await req('/v1/projects/'+project+'/secrets','PUT',hostToken,{name:'API_KEY',value:'private-value-fixture'})).status,403);
 const update=await req('/v1/projects/'+project+'/secrets','PUT',token,{name:'API_KEY',value:'private-value-fixture'});assert.equal(update.status,200);assert.ok(!JSON.stringify(update.body).includes('private-value'));
 const stored=(await pool.query('SELECT ciphertext FROM universe.runtime_secrets WHERE project_id=$1',[project])).rows[0];assert.ok(!stored.ciphertext.includes('private-value'));
 assert.equal((await req('/v1/tasks/'+task+'/secrets','POST',hostToken,{lease_token:randomUUID()})).status,409);
 const runtime=await req('/v1/tasks/'+task+'/secrets','POST',hostToken,{lease_token:lease});assert.equal(runtime.status,200);assert.equal(runtime.body.env.API_KEY,'private-value-fixture');
 for(const view of ['/v1/tasks/'+task,'/v1/events'])assert.ok(!JSON.stringify((await req(view,'GET',token)).body).includes('private-value-fixture'));
 await pool.query("UPDATE universe.tasks SET status='completed' WHERE id=$1",[task]);assert.equal((await req('/v1/tasks/'+task+'/secrets','POST',hostToken,{lease_token:lease})).status,409);
 }finally{delete process.env.SECRETS_ENCRYPTION_KEY;await api.close();await pool.end()}});
