import test from'node:test';import assert from'node:assert/strict';import pg from'pg';import{randomUUID}from'node:crypto';import{mkdtemp,rm}from'node:fs/promises';import{app}from'../control-plane/api/server.js';import{Store}from'../control-plane/api/store.js';import{digest,mint,permissions}from'../control-plane/authentication/auth.js';
test('shared Apex worker drives real Vertex/Postgres approval, deployment and service state (fake Docker)',{skip:!process.env.TEST_DATABASE_URL},async()=>{const workerPath='../host-worker/src/worker.js',apiPath='../host-worker/src/api.js',helpersPath='../host-worker/test/helpers.js';const{makeWorker}=await import(workerPath),{makeApi}=await import(apiPath),{makeArtifact,goodManifest,fakeDocker}=await import(helpersPath);const pool=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL}),tenant=randomUUID(),subject=randomUUID(),project=randomUUID(),host=randomUUID(),artifact=randomUUID(),token=mint(),hostToken=mint(),root=await mkdtemp('/tmp/shared-worker-');process.env.SUPABASE_URL='https://storage.test';process.env.SUPABASE_STORAGE_KEY='local-only-fixture';const server=app(new Store(pool),{allowHttp:true}),originalFetch=globalThis.fetch;const archive=makeArtifact(goodManifest('sample-app'));globalThis.fetch=async()=>Response.json({signedURL:'/object/sign/test?fixture=1'});try{
 await pool.query('INSERT INTO universe.tenants(id,name)VALUES($1,$2)',[tenant,'shared-test']);await pool.query('INSERT INTO universe.projects(id,tenant_id,name,owner)VALUES($1,$2,$3,$4)',[project,tenant,'sample-app',subject]);await pool.query('INSERT INTO universe.hosts(id,tenant_id,name,capabilities)VALUES($1,$2,$3,$4)',[host,tenant,'host',['deploy','stop']]);await pool.query("INSERT INTO universe.artifacts(id,tenant_id,project_id,filename,storage_path,checksum,size,version,verified)VALUES($1,$2,$3,'sample.tar.gz',$4,$5,$6,'v1',true)",[artifact,tenant,project,randomUUID(),archive.checksum,archive.buf.length]);for(const[id,tok,kind,scopes]of[[subject,token,'operator',permissions],[host,hostToken,'host',['worker','read_status']]])await pool.query("INSERT INTO universe.credentials(tenant_id,subject_id,kind,token_hash,scopes,expires_at)VALUES($1,$2,$3,$4,$5,now()+interval '1 hour')",[tenant,id,kind,digest(tok as string),scopes]);
 const request=async(path:string,method='GET',payload?:object)=>{const r=await server.inject({method:method as any,url:path,headers:{authorization:'Bearer '+token},payload});assert.equal(r.statusCode,200,r.body);return r.json()};
 const client=makeApi({baseUrl:'https://control.test',hostId:host,getToken:()=>hostToken,fetchImpl:async(url:string,opts:any={})=>{if(url.startsWith('https://storage.test'))return new Response(archive.buf);const r=await server.inject({method:opts.method||'GET',url:new URL(url).pathname,headers:opts.headers,payload:opts.body?JSON.parse(opts.body):undefined});return new Response(r.body,{status:r.statusCode,headers:{'content-type':'application/json'}})},sleep:async()=>{}});
 const docker=fakeDocker(),state:any={apps:{},seen_tasks:[],pending:{}},worker=makeWorker({api:client,docker,cfg:{appsDir:root+'/apps',cacheDir:root+'/cache',pollMs:1000,maxPerTick:1},state,save:async()=>{},version:'0.1.0',health:async()=>({ok:true}),metrics:async()=>({mem_free:8*1024**3,disk_free:10*1024**3,cpu_load_pct:0,uptime_s:1})});
 const created=await request('/v1/deployments','POST',{host_id:host,project_id:project,artifact_id:artifact,version:'v1',mode:'manual',idempotency_key:randomUUID()});await worker.tick();assert.equal(docker.calls.length,0);await request('/v1/tasks/'+created.id+'/approve','POST');await worker.tick();const task=await request('/v1/tasks/'+created.id);assert.equal(task.status,'completed');const deployments=await request('/v1/deployments');assert.equal(deployments[0].health_status,'healthy');assert.equal(deployments[0].container_ids.length,1);assert.ok(state.apps[project]);assert.ok(state.seen_tasks.includes(created.id));
 const stop=await request('/v1/services/'+deployments[0].id+'/stop','POST',{idempotency_key:randomUUID()});await worker.tick();assert.equal((await request('/v1/tasks/'+stop.id)).status,'completed');assert.equal((await request('/v1/deployments/'+deployments[0].id)).health_status,'stopped');
 }finally{globalThis.fetch=originalFetch;delete process.env.SUPABASE_URL;delete process.env.SUPABASE_STORAGE_KEY;await server.close();await pool.end();await rm(root,{recursive:true,force:true})}});
